name: sentiment_analysis
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - freetype=2.9.1
  - icu=58.2
  - intel-openmp=2020.0
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.0.1
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.0=166
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.8.2
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.9.7
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - tornado=6.0.4
  - wheel=0.34.2
  - zlib=1.2.11